version: '3.9'

services:
  front-minerva:
    container_name: front-minerva
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9092:3000"
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    networks:
      - minerva-network

networks:
  minerva-network:
    name: minerva-network