version: '3.9'

services:
  front-minerva:
    container_name: front-minerva
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - minerva-network

networks:
  minerva-network:
    name: minerva-network