openapi: 3.0.0
info:
  title: API Minerva
  contact: {}
  version: '1.0'
servers:
  - url: http://localhost:9091
    variables: {}
paths:
  /post:
    post:
      tags:
        - Post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                authorId:
                  type: integer
      responses:
        '201':
          description: Ok
        '400':
          description: Bad Request
  /post/all:
    get:
      tags:
        - Post
      responses:
        '200':
          description: Devuelve todos los Posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Post'
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        author:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            username:
              type: string
            website:
              type: string
            email:
              type: string
tags:
  - name: Post
    description: 'Minerva'