version: '3.9'

services:
  container-minerva:
    container_name: container-minerva
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    ports:
      - "9091:80"
    volumes:
      - .:/var/www/html
    networks:
      - minerva-network
  api-swagger-minerva:
    container_name: api-swagger-minerva
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./api_documentation.yaml:/api_documentation.yaml
    environment:
      SWAGGER_JSON: /api_documentation.yaml
    networks:
      - minerva-network
volumes:
  data-minerva:

networks:
  minerva-network:
    name: minerva-network