name: Build

on:
  push:
    branches: [ master ]
    paths:
      - "atenea/**"
      - ".github/workflows/build-atenea.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "atenea/**"
      - ".github/workflows/build-atenea.yml"

jobs:
  build-atenea:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/build.yml

      - name: Install Deps
        run: make deps

