name: Build-Atenea

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install docker-compose
        run: |-
          sudo apt-get install docker-compose
    
      - name: Version docker-compose
        run: |-
          docker-compose --version

      - name: Install Apps
        run: make start
