name: Tests

on:
  push:
    branches: [ master ]
    paths:
      - "atenea/**"
      - ".github/workflows/tests.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "atenea/**"
      - ".github/workflows/tests.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: |-
          cd atenea
          composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: |-
          cd atenea
          vendor/bin/phpunit